<?php

namespace Proxies\__CG__\OnSiteLube\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ServiceSchedule extends \OnSiteLube\AdminBundle\Entity\ServiceSchedule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'oilChgFilterMiles', 'oilChgFilterHours', 'oilChgFilterMonths', 'fuelFilterMiles', 'fuelFilterHours', 'airFilterMiles', 'airFilterHours', 'transFilterMiles', 'transFilterHours', 'transFilterMonths');
        }

        return array('__isInitialized__', 'id', 'name', 'oilChgFilterMiles', 'oilChgFilterHours', 'oilChgFilterMonths', 'fuelFilterMiles', 'fuelFilterHours', 'airFilterMiles', 'airFilterHours', 'transFilterMiles', 'transFilterHours', 'transFilterMonths');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ServiceSchedule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAirFilterHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirFilterHours', array());

        return parent::getAirFilterHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirFilterHours($airFilterHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirFilterHours', array($airFilterHours));

        return parent::setAirFilterHours($airFilterHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirFilterMiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirFilterMiles', array());

        return parent::getAirFilterMiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirFilterMiles($airFilterMiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirFilterMiles', array($airFilterMiles));

        return parent::setAirFilterMiles($airFilterMiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelFilterHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelFilterHours', array());

        return parent::getFuelFilterHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelFilterHours($fuelFilterHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelFilterHours', array($fuelFilterHours));

        return parent::setFuelFilterHours($fuelFilterHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelFilterMiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelFilterMiles', array());

        return parent::getFuelFilterMiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelFilterMiles($fuelFilterMiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelFilterMiles', array($fuelFilterMiles));

        return parent::setFuelFilterMiles($fuelFilterMiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getOilChgFilterHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOilChgFilterHours', array());

        return parent::getOilChgFilterHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setOilChgFilterHours($oilChgFilterHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOilChgFilterHours', array($oilChgFilterHours));

        return parent::setOilChgFilterHours($oilChgFilterHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getOilChgFilterMiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOilChgFilterMiles', array());

        return parent::getOilChgFilterMiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setOilChgFilterMiles($oilChgFilterMiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOilChgFilterMiles', array($oilChgFilterMiles));

        return parent::setOilChgFilterMiles($oilChgFilterMiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getOilChgFilterMonths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOilChgFilterMonths', array());

        return parent::getOilChgFilterMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setOilChgFilterMonths($oilChgFilterMonths)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOilChgFilterMonths', array($oilChgFilterMonths));

        return parent::setOilChgFilterMonths($oilChgFilterMonths);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransFilterHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransFilterHours', array());

        return parent::getTransFilterHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransFilterHours($transFilterHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransFilterHours', array($transFilterHours));

        return parent::setTransFilterHours($transFilterHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransFilterMiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransFilterMiles', array());

        return parent::getTransFilterMiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransFilterMiles($transFilterMiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransFilterMiles', array($transFilterMiles));

        return parent::setTransFilterMiles($transFilterMiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransFilterMonths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransFilterMonths', array());

        return parent::getTransFilterMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransFilterMonths($transFilterMonths)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransFilterMonths', array($transFilterMonths));

        return parent::setTransFilterMonths($transFilterMonths);
    }

}
