parameters:
#    on_site_lube_admin.example.class: OnSiteLube\AdminBundle\Example

services:
#    on_site_lube_admin.example:
#        class: %on_site_lube_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
