parameters:
#    on_site_lube_service.example.class: OnSiteLube\ServiceBundle\Example

services:
#    on_site_lube_service.example:
#        class: %on_site_lube_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
