<?php

namespace OnSiteLube\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AclRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AclRepository extends EntityRepository {


  /**
   * @return array
   */
  public function findAll() {
    $dql = "SELECT a.id, a.resourceId, a.permissionId FROM OnSiteLubeAdminBundle:Acl a";
    $query = $this->getEntityManager()->createQuery($dql);
    return $query->getResult();
  }

  /**
   * @param $userAccountId
   *
   * @return array
   */
  public function findByIdUserAcls($userAccountId) {
    $dql   = "select a.id, a.resourceId, a.permissionId, ua.id FROM OnSiteLubeAdminBundle:Acl a join a.userAccount ua ";
    $dql  .= "where ua.id = :userAccountId";
    $query = $this->getEntityManager()->createQuery($dql)
        ->setParameters(array('userAccountId' => $userAccountId));

    return $query->getResult();
  }

  /**
   * @param $service
   *
   * @return object
   */
  public static function findRepository($service) {
    return $service->getDoctrine()->getRepository('OnSiteLubeAdminBundle:Acl');
  }


}
