<?php

namespace OnSiteLube\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAuditRepository extends EntityRepository {

  /**
   * @param $userAccountId
   *
   * @return LoginAudit
   */
  public function createAuditLogEntry($userAccountId) {

    $em = $this->getEntityManager();

    $loginAudit = new LoginAudit();
    $loginAudit->setUserAccountId($userAccountId);
    $loginAudit->setLoginDateTime(new \DateTime());
    $em->persist($loginAudit);
    $em->flush();

    return $loginAudit;
  }

  /**
   * @param $service
   *
   * @return object
   */
  public static function findRepository($service) {
    return $service->getDoctrine()->getRepository('OnSiteLubeAdminBundle:LoginAudit');
  }

}
