<?php

namespace OnSiteLube\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceScheduleRepository extends EntityRepository {


  /**
   * @param $input
   *
   * @return ServiceSchedule
   */
  public function addServiceSchedule($input) {
    $em = $this->getEntityManager();

    $serviceSchedule = new ServiceSchedule();
    $serviceSchedule->setName($input->name);

    $serviceSchedule->setOilChgFilterMiles($input->oilFilterMiles);
    $serviceSchedule->setOilChgFilterHours($input->oilFilterHours);
    $serviceSchedule->setOilChgFilterMonths($input->oilFilterMonths);

    $serviceSchedule->setFuelFilterMiles($input->fuelFilterMiles);
    $serviceSchedule->setFuelFilterHours($input->fuelFilterHours);

    $serviceSchedule->setAirFilterMiles($input->airFilterMiles);
    $serviceSchedule->setAirFilterHours($input->airFilterHours);

    $serviceSchedule->setTransFilterMiles($input->transFilterMiles);
    $serviceSchedule->setTransFilterHours($input->transFilterHours);
    $serviceSchedule->setTransFilterMonths($input->transFilterMonths);

    $em->persist($serviceSchedule);
    $em->flush();

    return $serviceSchedule;
  }

  /**
   * @param $service
   *
   * @return object
   */
  public static function findRepository($service) {
    return $service->getDoctrine()->getRepository('OnSiteLubeAdminBundle:ServiceSchedule');
  }
} 