<?php

namespace OnSiteLube\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeCodeRepository extends EntityRepository {


  /**
   * @param $id
   *
   * @return array
   */
  public function findById($id) {
    $dql  = "SELECT tc.id, tc.name, tc.description ";
    $dql .= "FROM OnSiteLubeAdminBundle:TimeCode tc ";
    $dql .= "where tc.id = :timeCodeId";
    $query = $this->getEntityManager()->createQuery($dql)->setParameters(array('timeCodeId' => $id));
    return $query->getResult();
  }

  /**
   * @param $service
   *
   * @return object
   */
  public static function findRepository($service) {
    return $service->getDoctrine()->getRepository('OnSiteLubeAdminBundle:TimeCode');
  }
}
